server:
  port: 8888
spring:
  profiles:
    active: native
  application:
    name: config-server
  cloud:
    config:
      server:
        native: classpath:/config
        #git:
        # uri: https://github.com/githubvan/springcloud-config.git
        #  search-paths: /config-repo
        #  username: 15874803018@163.com
        #  password: qwer1624
        #  default-label: master





