server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/githubvan/springcloud-config.git   #git仓库的位置
          search-paths: /config-repo  #仓库下路径的相对位置
          username: 15874803018@163.com  #用户名
          password: qwer1624  #密码
          default-label: master




